spring:
  application:
    name: user-service

  config:
    import: "configserver:"

  cloud:
    config:
      uri: http://localhost:9000
#      uri: http://config.platform:9000

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB